/*
 demo tables for mariadb/mysql
 Table1: items
 Table2: vendors
 Date: 221115 
*/


-- ----------------------------
-- Table structure for items
-- ----------------------------
-- DROP TABLE ITEMS;
DROP TABLE ITEMS;

CREATE TABLE ITEMS (
  "itemId" number GENERATED BY DEFAULT AS IDENTITY,
  "itemName" varchar(100) NOT NULL,
  "itemVendorId" number(10,0) NOT NULL,
  "itemListPrice" number(10,2) NOT NULL,
  "itemModelYear" number(4,0) DEFAULT NULL,
  PRIMARY KEY ("itemId")
); 

-- ----------------------------
-- Table structure for vendors
-- ----------------------------
--DROP TABLE VENDORS;
DROP TABLE VENDORS;

CREATE TABLE VENDORS (
  "vendorId" number GENERATED BY DEFAULT AS IDENTITY,
  "vendorName" varchar(100),
  PRIMARY KEY ("vendorId")
);


